root: true
parser: '@typescript-eslint/parser'
plugins: ['@typescript-eslint', 'jest','sonarjs' ]
extends: ['eslint:recommended', 'plugin:@typescript-eslint/recommended', 'prettier','plugin:jest/recommended','plugin:sonarjs/recommended']

