name: continuous integration workflow

on: [push]

jobs:
  build:
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v2

      - name: Detect Node version from .nvmrc
        id: node_version
        run: echo "::set-output name=nvmrc::$(cat .nvmrc)"

      - uses: actions/setup-node@v2
        with:
          node-version: ${{ steps.node_version.outputs.nvmrc }}

      - name: npm-ci
        run: npm ci

      - name: build
        run: npm run vscode:prepublish

      - name: test
        run: npm run coverage
        
      - uses: codecov/codecov-action@v2
        with:
          token: ${{ secrets.CODECOV_TOKEN }} # not required for public repos
          files: ./coverage/clover.xml
          flags: unittests # optional
          verbose: true # optional (default = false)

      # - name: ui-test linux
      #   if: runner.os == 'Linux'
      # #  run: xvfb-run -a npm run ui-test
      #   uses: GabrielBB/xvfb-action@v1
      #   with:
      #     run: npm run ui-test
      
      # - name: ui-test linux
      #   if: runner.os != 'Linux'
      #   run: npm run ui-test
